DO $$ BEGIN
  CREATE TYPE "public"."user_role" AS ENUM ('user', 'admin');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "public"."intake_status" AS ENUM ('In Progress', 'Completed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "public"."sync_status" AS ENUM ('true', 'false');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  "name" text,
  "email" varchar(320),
  "loginMethod" varchar(64),
  "role" "user_role" DEFAULT 'user' NOT NULL,
  "createdAt" timestamptz DEFAULT now() NOT NULL,
  "updatedAt" timestamptz DEFAULT now() NOT NULL,
  "lastSignedIn" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "signupIntakes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" "intake_status" DEFAULT 'In Progress' NOT NULL,
  "conversationLog" text,
  "synced" "sync_status" DEFAULT 'false' NOT NULL,
  "syncedAt" timestamptz,
  "createdAt" timestamptz DEFAULT now() NOT NULL,
  "updatedAt" timestamptz DEFAULT now() NOT NULL
);
