CREATE TABLE `signupIntakes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`status` enum('In Progress','Completed') NOT NULL DEFAULT 'In Progress',
	`companyName` varchar(255),
	`ein` varchar(64),
	`businessEntity` varchar(128),
	`ownerFirstName` varchar(128),
	`ownerLastName` varchar(128),
	`ownerEmail` varchar(320),
	`ownerPhone` varchar(64),
	`ownerTitle` varchar(128),
	`contactFirstName` varchar(128),
	`contactLastName` varchar(128),
	`contactEmail` varchar(320),
	`contactPhone` varchar(64),
	`contactTitle` varchar(128),
	`businessStreet` varchar(255),
	`businessCity` varchar(128),
	`businessState` varchar(64),
	`businessZip` varchar(20),
	`billingSameAsBusiness` varchar(8),
	`billingStreet` varchar(255),
	`billingCity` varchar(128),
	`billingState` varchar(64),
	`billingZip` varchar(20),
	`adminUsers` text,
	`conversationLog` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `signupIntakes_id` PRIMARY KEY(`id`)
);
