ALTER TABLE `signupIntakes` DROP INDEX `signupIntakes_sessionId_unique`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `sessionId`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `companyName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `dba`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ein`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessType`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessEntity`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerFirstName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerLastName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerEmail`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerPhone`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerPhoneExt`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `ownerTitle`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactFirstName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactLastName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactEmail`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactPhone`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactPhoneExt`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactMobilePhone`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `contactTitle`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessStreet`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessStreet2`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessCity`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessState`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessZip`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `businessCountry`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingSameAsBusiness`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingStreet`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingStreet2`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingCity`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingState`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingZip`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingCountry`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `billingAttention`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `adminUsers`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `authorizedSignature`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `signatureDate`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `signatureName`;--> statement-breakpoint
ALTER TABLE `signupIntakes` DROP COLUMN `signatureTitle`;